### ISSUE TITLE
re-evaluate the track

### ISSUE THREAD

**Issue by NobbZ** [exercism/xerlang#107]
After there has been the idea to use `rebar3` in #106, I already mentioned a re-evaluation of the track in that thread.

For this re-evaluation, I do think, we need to achieve quite a lot, and I'd also like to put the further inclusion of exercises on hold until this re-evaluation has been finished.

Currently I do see the following sub-tasks which should be part of this re-evaluation:
- re-order exercises
  - classify exercises by difficulty
  - classify exercises by "kind" (lists, recursion, math, concurrency, etc)
  - make them suitable to run using OTP 17 to 19 in the latest release respectively
- use generators for exercises when there are `.json`s in x-common available.
- use rebar3 to run tests/compile exercises
  - keep `eunit` as testing framework
  - perhaps add dialyzer config for optional type checking

I'd like to start with the re-evaluation of the exercises, but I am near my personal limit after having exam phase at my university right now while also started a new job 2 weeks ago.

So I leave this open for discussion at first, and I'd also would be happy if @kytrinyx could ask for volunteers in the blog/newsletter that are eager to help and have different levels of experience with erlang (from totally new to professional) to get some opinions about the difficulty of the exercises.

@exercism/erlang

**Comment by kytrinyx** [comment]
> I'd also would be happy if @kytrinyx could ask for volunteers in the blog/newsletter that are eager to help and have different levels of experience with erlang (from totally new to professional) to get some opinions about the difficulty of the exercises.

Yes, good call. I'll put that in this weekends newsletter.

**Comment by NobbZ** [comment]
To make stuff a little bit easier I created another repository: https://github.com/NobbZ/xerlang-reclassification

People who don't want to fork may drop a message in this thread as well, I will update the remote repository accordingly (not more than once a day).

**Comment by hfenton** [comment]
🙋 I would like to help.  Is there anything you need from me?

**Comment by kytrinyx** [comment]
@NobbZ Would you describe the step-by-step process that people can use to help out?

**Comment by NobbZ** [comment]
Of course I can. I do hope I will find some time about this evening (Europe time).

**Comment by NobbZ** [comment]
OK, So I try a step by step here:

1. Do an erlang exercise at exercism.
2. Take a note how easy it was on a scale from 1 to 10, while 1 beeing the easiest and 10 beeing the hardest possible things.
3. Write down a collection of tags you would assign to this exercise (there is a collection of possible tags in https://github.com/exercism/discussions/issues/60#issuecomment-237163857)
4. Tell me what you have written down in steps 2 and 3, either by PR'ing https://github.com/NobbZ/xerlang-reclassification, or by filing an issue there, or reporting back here.
5. repeat from step 1 until you have done a couple of exercises ;)

There is no need to do a report for every single exercise, you may skip as you want, but of course I am happy about every single report.

**Comment by NobbZ** [comment]
Close by #132
