### ISSUE TITLE
erl -make gives me "init terminating in do_boot"

### ISSUE THREAD

**Issue by paulnice** [exercism/xerlang#113]
Hello,

I'm trying to make a first task in the erlang track. When I execute 'erl -make' command it gives me the error.

ps@linux:~/exercism/erlang/hello-world$ erl -make
{"init terminating in do_boot",{undef,[{make,all_or_nothing,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
ps@linux:~/exercism/erlang/hello-world$ erl
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V8.0  (abort with ^G)
1>

**Comment by NobbZ** [comment]
I can't reproduce the behviour you describe, and I tried OTP 16, 17, 18, 19 in their latest release each.

Can you try `erlc *.erl` instead of `erl -make`? You should have a file ending in `.beam` for each file ending in `.erl` then. If that succeeds, please try to continue using `erl -noshell -eval "eunit:test(hello_world, [verbose])" -s init stop`

If this does work, you can decide to live with that workaround or to continue with the step does not work ;)

If it does not work this way, please give some more information about your system. To be exact: which linux distro are you using, which erlang related packages have you installed and from what sources? Did you even did an installation from source? Did you use any version managers? If so, which one?

**Comment by paulnice** [comment]
ps@linux:~/exercism/erlang/hello-world$ erlc *.erl
hello_world.erl:3: Warning: function greet/1 is unused
hello_world_tests.erl: undefined parse transform 'eunit_autoexport'

ps@linux:~/exercism/erlang/hello-world$ ls -la *.beam
-rw-rw-r-- 1 ps ps 484 Sep 19 22:03 hello_world.beam

erl -noshell -eval "eunit:test(hello_world, [verbose])" -s init stop
{"init terminating in do_boot",{undef,[{eunit,test,[hello_world,[verbose]],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()

It doesn't work for me. Sorry :(

I'm using:
Ubuntu Linux 16.04 amd64
$ dpkg -l | grep erlang
ii  erlang-asn1                                 1:19.0-1                                                    amd64        Erlang/OTP modules for ASN.1 support
ii  erlang-base                                 1:19.0-1                                                    amd64        Erlang/OTP virtual machine and base applications
ii  erlang-crypto                               1:19.0-1                                                    amd64        Erlang/OTP cryptographic modules
ii  erlang-dev                                  1:19.0-1                                                    amd64        Erlang/OTP development libraries and headers
ii  erlang-inets                                1:19.0-1                                                    amd64        Erlang/OTP Internet clients and servers
ii  erlang-mnesia                               1:19.0-1                                                    amd64        Erlang/OTP distributed relational/object hybrid database
ii  erlang-public-key                           1:19.0-1                                                    amd64        Erlang/OTP public key infrastructure
ii  erlang-runtime-tools                        1:19.0-1                                                    amd64        Erlang/OTP runtime tracing/debugging tools
ii  erlang-solutions                            1.0                                                         all          A package to add repository.
ii  erlang-ssl                                  1:19.0-1                                                    amd64        Erlang/OTP implementation of SSL
ii  erlang-syntax-tools                         1:19.0-1                                                    amd64        Erlang/OTP modules for handling abstract Erlang syntax trees

Package: erlang-base
Versions: 
1:19.0-1 (/var/lib/apt/lists/binaries.erlang-solutions.com_debian_dists_xenial_contrib_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/binaries.erlang-solutions.com_debian_dists_xenial_contrib_binary-amd64_Packages
                  MD5: eb27cf1ed982601f2dcb1802ba9d4396
 Description Language: 
                 File: /var/lib/apt/lists/binaries.erlang-solutions.com_debian_dists_xenial_contrib_binary-amd64_Packages
                  MD5: eb27cf1ed982601f2dcb1802ba9d4396
 Description Language: 
                 File: /var/lib/apt/lists/binaries.erlang-solutions.com_debian_dists_xenial_contrib_binary-i386_Packages
                  MD5: eb27cf1ed982601f2dcb1802ba9d4396

I haven't done any installation from sources. I installed this system 3 weeks ago. So it's still kind of clean.
I don't use any version managers.

**Comment by NobbZ** [comment]
It seems as if you are using debian or ubuntu paired with erlang solutions package repositories, so please install `erlang-euint` package.

**Comment by paulnice** [comment]
ps@linux:~/exercism/erlang/hello-world$ sudo apt-get install erlang-euint
[sudo] password for ps: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package erlang-euint

I'll find out how to fix this eunit issue. But I suspect the eunit issue and the "init terminating" issue is not connected to each other.

**Comment by paulnice** [comment]
I've installed erlang-eunit (previously there was a typo 'euint' vs 'eunit').
Now erlc *.beam works, but erl -make doesn't:

ps@linux:~/exercism/erlang/hello-world$ erl -make *.erl
{"init terminating in do_boot",{undef,[{make,all_or_nothing,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
ps@linux:~/exercism/erlang/hello-world$ erlc *.erl
hello_world.erl:3: Warning: function greet/1 is unused

**Comment by paulnice** [comment]
It looks like I don't have make module installed.

ps@linux:~/exercism/erlang/hello-world$ erl
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V8.0  (abort with ^G)
1> make:all(). 
** exception error: undefined function make:all/0

**Comment by paulnice** [comment]
Installing erlang-tools solves the problem.

(Next time I have to install all-in-one esl-erlang package. I spent too much time for nothing troubleshooting this output). Sorry for bothering you and for the extra-issue conversation.

ps@linux:~/exercism/erlang/hello-world$ sudo apt-get install erlang-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  erlang erlang-manpages erlang-doc
The following NEW packages will be installed:
  erlang-tools
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 522 kB of archives.
After this operation, 1,152 kB of additional disk space will be used.
Get:1 http://packages.erlang-solutions.com/debian xenial/contrib amd64 erlang-tools amd64 1:19.0-1 [522 kB]
Fetched 522 kB in 2s (181 kB/s)        
Selecting previously unselected package erlang-tools.
(Reading database ... 251979 files and directories currently installed.)
Preparing to unpack .../erlang-tools_1%3a19.0-1_amd64.deb ...
Unpacking erlang-tools (1:19.0-1) ...
Setting up erlang-tools (1:19.0-1) ...
ps@linux:~/exercism/erlang/hello-world$ erl -make
ps@linux:~/exercism/erlang/hello-world$
