### ISSUE TITLE
Add helpful information to the SETUP.md

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xerlang#33]
The contents of the SETUP.md file gets included in
the README.md that gets delivered when a user runs the `exercism fetch`
command from their terminal.

At the very minimum, it should contain a link to the relevant
language-specific documentation on
[help.exercism.io](http://help.exercism.io).

It would also be useful to explain in a generic way how to run the tests.
Remember that this file will be included with _all_ the problems, so it gets
confusing if we refer to specific problems or files.

Some languages have very particular needs in terms of the solution: nested
directories, specific files, etc. If this is the case here, then it would be
useful to explain what is expected.

------

Thanks, @tejasbubane for suggesting that we add this documentation everywhere.
See [exercism.io#2198](https://github.com/exercism/exercism.io/issues/2198).

**Comment by tmcgilchrist** [comment]
Sounds like a good idea, you want the starting experience to be a seamless as possible. 
I'll have a go at writing something unless someone else beats me to it.

What's the best way to see how the final README.md looks when running `exercism fetch`? I haven't really stepped outside the `xerlang` and `xocaml` repos.

**Comment by kytrinyx** [comment]
There's no real easy way to do this at the moment. I tend to run a local version of the `x-api` server and then request the /problems/:track_id/:problem_slug endpoint. I'll try to come up with a handier way of doing that.
