### ISSUE TITLE
Implement Erlang exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xerlang#4]
See exercism/exercism.io#874 and erlsyd/exercism.io#1

----

* [x] bob
* [x] word-count
* [x] anagram
* [x] beer-song
* [x] nucleotide-count
* [x] rna-transcription
* [x] point-mutations
* [x] phone-number
* [x] etl
* [x] grade-school
* [x] leap
* [x] meetup
* [x] space-age
* [x] grains
* [x] gigasecond
* [x] triangle
* [ ] scrabble-score
* [ ] roman-numerals
* [x] binary
* [ ] prime-factors
* [ ] raindrops
* [x] allergies
* [x] strain
* [x] atbash-cipher
* [x] accumulate
* [ ] nth-prime
* [ ] palindrome-products
* [x] sum-of-multiples
* [x] bank-account
* [ ] minesweeper
* [x] parallel-letter-frequency
* [ ] zipper
* [ ] sieve
* [ ] pythagorean-triplet
* [x] difference-of-squares
* [x] largest-series-product
* [ ] queen-attack
* [ ] saddle-points
* [ ] ocr-numbers
* [ ] pascals-triangle
* [ ] say
* [ ] crypto-square
* [x] trinary
* [ ] simple-cipher
* [ ] octal
* [x] luhn
* [ ] pig-latin
* [x] series
* [ ] secret-handshake
* [ ] linked-list
* [ ] wordy
* [ ] hexadecimal
* [ ] kindergarden-garden
* [ ] binary-search-tree
* [ ] matrix
* [x] robot

**Comment by defndaines** [comment]
"allergies" and "meetup" are now included. I also have working examples and tests for "grains" and "gigasecond" that I hope to submit in a day or so.

**Comment by tmcgilchrist** [comment]
Marked "grains" and "gigasecond" as done.

**Comment by kytrinyx** [comment]
We have a new process that you can use to find exercises to implement.
You can read all about it [here](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track).

I'm closing this issue in favor of the process described in the Contributing guide linked to above.

Thanks!

**Comment by tmcgilchrist** [comment]
Nice.
