### ISSUE TITLE
etl tests seem dubious

### ISSUE THREAD

**Issue by macintux** [exercism/xerlang#63]
`transform_multiple_keys_from_one_value_test` violates the goals stated in the README, and generally the tests are confusing because they invert letters and scores (or abandon letters and scores entirely).

The problem with `transform_multiple_keys_from_one_value_test`: it's nonsensical to have the same Scrabble letter with two different scores (setting aside the language discussion from the end of the README; if you're going to collapse multiple languages into the same list of letters/scores, you need some way to differentiate them).

**Comment by NobbZ** [comment]
Since #64 has been merged, can't this one get closed?

**Comment by kytrinyx** [comment]
Yepp, it sure can. Thanks.
