### ISSUE TITLE
Intruducing a version test-case

### ISSUE THREAD

**Issue by NobbZ** [exercism/xerlang#73]
In an exercise (http://exercism.io/submissions/05fb1f5acd00405aaa36844167c8d603) we assumed that an older test was used, and two of us thought it might be helpfull for thinks like this to have something that tells which version of the testsuite was used.

In the xruby path, there is one test in every suite which tests for the value of a constant of the module/class under test.

An example could be the following

``` erl
-module(example_tests).

-define(TEST_VERSION, 1).

version_test() -> ?assertMatch(?TEST_VERSION, example:version()).
```

**Comment by kytrinyx** [comment]
We've got these in Go as well. It certainly helps people feel a little bit less miffed when the test suite changes out from under them.

**Comment by barberj** [comment]
@kytrinyx so is that an approval or does @tmcgilchrist need to weigh in?

**Comment by kytrinyx** [comment]
I approve in a generic sense. We need one of the people on the @exercism/erlang team to do the merge, though, since they know the specifics of the track.

**Comment by NobbZ** [comment]
Has this already been disussed in the @exercism/erlang team? This hasn't been touched for a month now.

**Comment by kytrinyx** [comment]
If nobody weighs in in the next 24 hours, I'll merge it.

**Comment by NobbZ** [comment]
There's nothing to merge ;) This shall just be a discussion about if we shall introduce some constant value into the testsuites that determine the suites version, as it is done in several other tracks (I know about xruby, you already mentioned xgo)

**Comment by kytrinyx** [comment]
Oh, right :)

**Comment by NobbZ** [comment]
Since I was promoted to a maintainer, I will take this one and will start to update the tests accordingly during the next two weeks while taking on #82 at the same time.

**Comment by tmcgilchrist** [comment]
Late to the party on this but this sounds like a good idea.
