### ISSUE TITLE
Move exercises to subdirectory

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xerlang#82]
The problems api (x-api) now supports having exercises collected in a subdirectory
named `exercises`.

That is to say that instead of having a mix of `bin`, `docs`, and individual exercises,
we can have `bin`, `docs`, and `exercises` in the root of the repository, and all
the exercises collected in a subdirectory.

In other words, instead of this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── bowling
│   ├── bowling_test.ext
│   └── example.ext
├── clock
│   ├── clock_test.ext
│   └── example.ext
├── config.json
└── docs
│   ├── ABOUT.md
│   └── img
... etc
```

we can have something like this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── config.json
├── docs
│   ├── ABOUT.md
│   └── img
├── exercises
│   ├── bowling
│   │   ├── bowling_test.ext
│   │   └── example.ext
│   └── clock
│       ├── clock_test.ext
│       └── example.ext
... etc
```

This has already been deployed to production, so it's safe to make this change whenever you have time.

**Comment by NobbZ** [comment]
I want to take this one and spread the work over the next two weeks while updating the tests in accordance to #73.

So I have a question about how your system deals with a partial move.
Before merging the update, need all exercises to be moved into the subdirectory, or would everything work when there is only a single one moved and all others are still in a toplevel directory?

**Comment by kytrinyx** [comment]
Partial/piecemeal move is perfectly acceptable. Right now it checks the new location first for a given exercise, then checks the old location as a fallback.

**Comment by tmcgilchrist** [comment]
Thanks for doing the move work @NobbZ

**Comment by NobbZ** [comment]
So I'll move scrabble score and update this PR in the next 12 hours.

**Comment by tmcgilchrist** [comment]
Done!
