### ISSUE TITLE
Launch Erlang track?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xerlang#9]
We have enough exercises to launch:

```plain
accumulate
allergies
anagram
beer-song
bob
etl
luhn
nucleotide-count
phone-number
point-mutations
rna-transcription
trinary
word-count
```

In order to get this launched, we need to:

1. Figure out roughly how to order these by increasing difficulty
2. Stick that ordered list into `config.json` under `"problems"`
3. Flip the `"active"` property to true in `config.json`
4. Make sure we have a couple people around who know enough erlang to help nitpick in the early days

**Comment by NobbZ** [comment]
Can't this be closed? Erlang track is available for some time now.

**Comment by kytrinyx** [comment]
Yeah, definitely. Thanks.
