### ISSUE TITLE
binary: improve tests for invalid numbers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xerlang#96]
We should have separate tests for:

- alphabetic characters at the beginning of a valid binary number
- alphabetic characters at the end of a valid binary number
- alphabetic characters in the middle of an otherwise valid binary number
- invalid digits (e.g. 2)

If the test suite for binary has test cases that cover these edge cases, this issue can safely be closed.

See https://github.com/exercism/x-common/issues/95

**Comment by NobbZ** [comment]
I'd prefer to have a JSON with testdata before fixing this. Fixing without might introduce additional noise when there appears common testdata.

**Comment by NobbZ** [comment]
Since we are in the process of deprecating `binary` along other exercises in a big sweep (exercism/x-common#279), I think we can close this, can't we?

**Comment by kytrinyx** [comment]
agreed, thanks!
